project_id = "boskgmampbfccbfpgzea"

[functions.reformat-notes]
verify_jwt = false

[functions.format-soap-notes]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.generate-prescription-pdf]
verify_jwt = false

[functions.invite-staff]
verify_jwt = false

[functions.remove-staff]
verify_jwt = false

[functions.send-lab-order]
verify_jwt = false

[functions.summarize-lab-result]
verify_jwt = false