// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-patients.ts
import { createClient } from "npm:@supabase/supabase-js@^2.107.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function supa(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_patients_default = defineTool({
  name: "search_patients",
  title: "Search patients",
  description: "Search patients in the signed-in user's clinic by name, phone, or email. Returns up to 20 matches.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Free-text query matched against name, phone, or email.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const like = `%${query.replace(/[%_]/g, "")}%`;
    const { data, error } = await supa(ctx).from("patients").select("id, full_name, phone, email, created_at").or(`full_name.ilike.${like},phone.ilike.${like},email.ilike.${like}`).limit(20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { patients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-appointments.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.107.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supa2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_appointments_default = defineTool2({
  name: "list_appointments",
  title: "List appointments",
  description: "List appointments in the signed-in user's clinic for a given date (YYYY-MM-DD). Defaults to today.",
  inputSchema: {
    date: z2.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Date in YYYY-MM-DD. Defaults to today (UTC).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const d = date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const { data, error } = await supa2(ctx).from("appointments").select("id, patient_id, appointment_date, appointment_time, status, doctor_id, notes").eq("appointment_date", d).order("appointment_time", { ascending: true }).limit(200);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { date: d, appointments: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-therapy-sessions.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.107.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supa3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_therapy_sessions_default = defineTool3({
  name: "list_therapy_sessions",
  title: "List therapy sessions",
  description: "List therapy sessions in the signed-in user's clinic for a given date (YYYY-MM-DD). Defaults to today.",
  inputSchema: {
    date: z3.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Date in YYYY-MM-DD. Defaults to today (UTC).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const d = date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const { data, error } = await supa3(ctx).from("therapy_sessions").select("id, patient_id, therapist_id, service_id, session_date, status, started_at, completed_at").eq("session_date", d).order("session_date", { ascending: true }).limit(200);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { date: d, sessions: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "amipgrjksrszocfzucxn";
var mcp_default = defineMcp({
  name: "flowcare-mcp",
  title: "FlowCare Clinic MCP",
  version: "0.1.0",
  instructions: "Tools for a FlowCare clinic account. Search patients, list appointments and therapy sessions for a given date. All data is scoped to the signed-in user's clinic.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_patients_default, list_appointments_default, list_therapy_sessions_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
